person:
    resource: "@PersonBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
contact:
    path: /contact
    defaults: { _controller: AppBundle:Main:contact }

_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
